require("material").setup({
	contrast = {
		terminal = true,
		sidebars = false,
		cursor_line = false,
		floating_windows = true,
		non_current_windows = false,
		filetypes = {},
	},
	styles = {
		comments = { italic = true },
		strings = {},
		keywords = { bold = true },
		functions = { bold = true },
		variables = { bold = true },
		operators = { bold = true },
		types = {},
	},
	plugins = {},
	disable = {
		colored_cursor = false,
		borders = false,
		background = false,
		term_colors = false,
		eob_lines = false,
	},
	high_visibility = {
		lighter = false,
		darker = false,
	},
	lualine_style = "default",
	custom_colors = nil,
	custom_highlights = {},
	async_loading = true,
})
