# Enable Powerlevel10k instant prompt. should stay close to the top of ~/.zshrc.
# initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${xdg_cache_home:-$home/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${xdg_cache_home:-$home/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# if you come from bash you might have to change your $path.
# export path=$home/bin:/usr/local/bin:$path

# path to your oh-my-zsh installation.
export zsh="$home/.oh-my-zsh"

# set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $random_theme
# see https://github.com/ohmyzsh/ohmyzsh/wiki/themes
zsh_theme="powerlevel10k/powerlevel10k" # set by `omz`

# set list of themes to pick from when loading at random
# setting this variable when zsh_theme=random will cause zsh to load
# a theme from this variable instead of looking in $zsh/themes/
# if set to an empty array, this variable will have no effect.
# zsh_theme_random_candidates=( "robbyrussell" "agnoster" )

# uncomment the following line to use case-sensitive completion.
# case_sensitive="true"

# uncomment the following line to use hyphen-insensitive completion.
# case-sensitive completion must be off. _ and - will be interchangeable.
# hyphen_insensitive="true"

# uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic update
zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# uncomment the following line if pasting urls and other text is messed up.
# disable_magic_functions="true"

# uncomment the following line to disable colors in ls.
# disable_ls_colors="true"

# uncomment the following line to disable auto-setting terminal title.
# disable_auto_title="true"

# uncomment the following line to enable command auto-correction.
enable_correction="true"

# uncomment the following line to display red dots whilst waiting for completion.
# you can also set it to another string to have that shown instead of the default red dots.
# e.g. completion_waiting_dots="%f{yellow}waiting...%f"
# caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# completion_waiting_dots="true"

# uncomment the following line if you want to disable marking untracked files
# under vcs as dirty. this makes repository status check for large repositories
# much, much faster.
disable_untracked_files_dirty="true"

# uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# you can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
hist_stamps="mm/dd/yyyy"

# would you like to use another custom folder than $zsh/custom?
# zsh_custom=/path/to/new-custom-folder

# which plugins would you like to load?
# standard plugins can be found in $zsh/plugins/
# custom plugins may be added to $zsh_custom/plugins/
# example format: plugins=(rails git textmate ruby lighthouse)
# add wisely, as too many plugins slow down shell startup.
plugins=(
  aliases
  fzf
  kitty
  tmux
  tmux-cssh
  tmuxinator
  vim-interaction
  zoxide
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

# nvim path 
export path="$path:$home/nvim-linux64/bin/nvim"

# source the omz at shell initiation
source $zsh/oh-my-zsh.sh

# user configuration
# export manpath="/usr/local/man:$manpath"

# you may need to manually set your language environment
export lang=en_us.utf-8

# preferred editor for local and remote sessions
if [[ -n $ssh_connection ]]; then
    export editor='nvim'
else
    export editor='vi'
fi

# compilation flags
# export archflags="-arch x86_64"


export nvm_dir="$home/.nvm"
[ -s "$nvm_dir/nvm.sh" ] && \. "$nvm_dir/nvm.sh"  # this loads nvm
[ -s "$nvm_dir/bash_completion" ] && \. "$nvm_dir/bash_completion"  # this loads nvm bash_completion

# go setup
export path=$path:/usr/local/go/bin

# most
export pager="most"


# extended glob and null glob 
setopt extended_glob null_glob


# ============================= aliases ===============================
# info: aliases 

# set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the zsh_custom folder.
# for a full list of active aliases, run `alias`.
#
# example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# zsh conf 
alias zconf="nvim ~/.zshrc"
alias zs='source $home/.zshrc'

# kitty conf 
alias kconf="nvim /home/gokayburuc/.config/kitty/kitty.conf"

# fish conf
alias fconf="nvim $home/.config/fish/config.fish"

# tmux shortcuts 
alias tconf="nvim ~/.tmux.conf"
alias t="tmux"
alias tn="tmux new" 
alias ta="tmux attach-session"
alias trw="tmux rename-window"
alias trs="tmux rename-session"
alias tsw="tmux splitw"

# app operations
alias app_i="sudo apt install"
alias app_s="sudo apt search"
alias app_r="sudo apt remove"

# system operations
alias sfu="sudo apt update && sudo apt upgrade && sudo apt autoclean && sudo apt autoremove && sudo apt autopurge"
alias scl="sudo apt autoclean && sudo apt autoremove && sudo apt autopurge"

# flat
alias flatr="flatpak remove"
alias flati="flatpak install"

# lsd
alias ls='lsd'
alias lsa="lsd -a"

#tar
alias zpc="tar czf"
alias zpx="tar xvf"


# listen music 
alias lmusic='cd ~/music/ && rg --files --glob "*.mp3" | fzf --multi --reverse --prompt="song: " | xargs mpv --audio-display=no' 

# sys update 
alias syu="sudo apt update && sudo apt upgrade && sudo apt autoclean && sudo apt autopurge && sudo apt autoremove"

# lynx
alias ahref='lynx -dump -nonumbers -list-only'

# folder size management
alias fsize="du -had1 | sort -hr"

## foldershortcuts 
alias ob="cd /$home/documents/workspace/static_website/hugo/gokayburuc_weblog/"
alias og="cd /$home/documents/workspace/static_website/mdbook/golang_cookbook/"
alias ol="cd /$home/documents/lyrics/"
alias ov="cd /$home/documents/vaults/"
alias ow="cd /$home/documents/workspace"
alias oc="cd /$home/.config/nvim/"
alias oa="cd /$home/documents/ankiweb/"
alias ot="cd /$home/downloads/telegram\ desktop"

# fd 
fdm(){
  md "$2" # create folder using mkdir -p 
  fd "$1" --exec mv {} "$2" \;
}

## vault management 
nn() {
  # go to programming directory
  cd "$home/documents/vaults/programming/00-inbox/" || return

  # get current date
  current_date=$(date +"%y-%m-%d")

  # create filename
  filename="${current_date}_$1.md"

  # create the file
  touch "$filename"

  # open the created file with nvim
  nvim "$filename"
}


# bat 
alias bat="bat -pp"

# lazygit 
alias lg="lazygit"

# lazydocker 
alias lzd='lazydocker'

# brightness - reduce the brightness
alias loff="sudo brightnessctl set 75%"

# flatpak runners 
alias obsidian='flatpak run md.obsidian.obsidian'
alias minder='flatpak run com.github.phase1geo.minder'

# warn: use this to hide api keys 
# info: get keys from external file 
source ~/.keys.sh


# zoxide
eval "$(zoxide init zsh)"

#=============================== custom functions =============================== 

# note: leap into any file 

oo() {
  fd --hidden --follow | fzf --reverse --prompt="filename: " | xargs nvim
}

# note:  neovide 

oov(){

  fd --hidden --follow | fzf --reverse --prompt="filename: " | xargs neovide
}





## info: ffmpeg converter
convert_webp() {
  for i in *
  do
    ## info: if extension is sh then do this
    if [[ "${i##*.}" == "webp" ]]; then
      echo "pdf file => $i"
      # fix: show filename ,
      filename="${i%.*}"
      # fix: show extension 
      extension="${i##*.}"

      ## webp converter 
      ffmpeg -i "$filename" "$filename.png"

    fi
  done

    # ffmpeg -i "$1" "$2.png"
  }


## info: filename converter 

fcon ()
{
for i in $(rg --files); do

  new=$(echo "$i" | tr "[:upper:]" "[:lower:]" |  tr " " "-" | tr "_" "-" | tr "ı" "i" | tr "ş" "s" | tr "ğ" "g" | tr "ü" "u" | tr "ö" "o" | tr "ç" "c" )
  echo "$new"

  mv "$i" "$new" 
  echo "rename: '$i' -> '$new' "

done
}

## info: classify 

folderput(){
  # query
  query=$1 
  # folder 
  foldername=$2 

  md $foldername 

  fd "$query" --exec mv {} $foldername \;
}

# note: vault new note 
vn(){
  ov  # open vault
  local filename="$1"
  if [[ -z "$filename" ]]; then
    echo "usage: vn <filename>"
    return 1
  fi
  nvim "00_inbox/${filename}.md" # enter file-name and directly start writing 
}

empty-cache(){
  # sudo sh -c 'echo 1 >  /proc/sys/vm/drop_caches' # to clear pagecache only
  # sudo sh -c 'echo 2 >  /proc/sys/vm/drop_caches' # to clear dentries and inodes
  sudo sh -c 'echo 3 >  /proc/sys/vm/drop_caches' # to clear pagecache, dentries and inodes
  # sudo h -c 'echo 1 > /proc/sys/vm/drop_caches'  # clearing buffer/cache in linux
  sudo sync 
}


# fix: how to use | in bash functions 

rgf() {
  rg --files | rg "$1" --smart-case
}


# path 
export path="$home/.local/bin:$path"
export path="$home/documents/workspace/bash/:$path"

## elixir kiex path 
[[ -s "$home/.kiex/scripts/kiex" ]] && source "$home/.kiex/scripts/kiex"

# pnpm
export pnpm_home="/home/gokayburuc/.local/share/pnpm"
case ":$path:" in
  *":$pnpm_home:"*) ;;
  *) export path="$pnpm_home:$path" ;;
esac
# pnpm end

# info: rg & fzf 
# if type rg &> /dev/null; then
#   export fzf_default_command='rg --files'
#   export fzf_default_opts='-m --reverse --height 50% --border '
# fi


# --------------- fzf gruvbox ---------------------

local color00='#32302f'
local color01='#3c3836'
local color02='#504945'
local color03='#665c54'
local color04='#bdae93'
local color05='#d5c4a1'
local color06='#ebdbb2'
local color07='#fbf1c7'
local color08='#fb4934'
local color09='#fe8019'
local color0a='#fabd2f'
local color0b='#b8bb26'
local color0c='#8ec07c'
local color0d='#83a598'
local color0e='#d3869b'
local color0f='#d65d0e'

export fzf_default_opts="$fzf_default_opts"\
" --color=bg+:$color01,bg:$color00,spinner:$color0c,hl:$color0d"\
" --color=fg:$color04,header:$color0d,info:$color0a,pointer:$color0c"\
" --color=marker:$color0c,fg+:$color06,prompt:$color0a,hl+:$color0d"

# fix:  fzf kanagawa colors 


# info fzf & fd 
if type fd &> /dev/null; then
  export fzf_default_command='fd'
  export fzf_default_opts='-m --reverse --height 50% --border '
fi

# neovide path 
export path="$home/.cargo/bin:$path"
export path="$home/snap/neovide:$path"

# to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
