# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="gentoo" # set by `omz`

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic update
zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( fzf tmux zoxide zsh-completions zsh-autosuggestions zsh-syntax-highlighting aliases)

# nvim path 
export PATH="$PATH:$HOME/nvim-linux64/bin/nvim"

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='nvim'
else
    export EDITOR='vi'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# go setup
export PATH=$PATH:/usr/local/go/bin

# most
export PAGER="most"


# extended glob and null glob 
setopt extended_glob null_glob


# ============================= ALIASES ===============================
# INFO: Aliases 

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# zsh conf 
alias zconf="nvim ~/.zshrc"
alias zs='source $HOME/.zshrc'

# kitty conf 
alias kconf="nvim /home/gokayburuc/.config/kitty/kitty.conf"

# fish conf
alias fconf="nvim $HOME/.config/fish/config.fish"

# tmux shortcuts 
alias tconf="nvim ~/.tmux.conf"
alias t="tmux"
alias tn="tmux new" 
alias ta="tmux attach-session"
alias trw="tmux rename-window"
alias trs="tmux rename-session"

# app operations
alias app_i="sudo apt install"
alias app_s="sudo apt search"
alias app_r="sudo apt remove"

# system operations
alias sys_fu="sudo apt update && sudo apt upgrade && sudo apt autoclean && sudo apt autoremove && sudo apt autopurge"
alias sys_cl="sudo apt autoclean && sudo apt autoremove && sudo apt autopurge"

# flat
alias flat_r="flatpak remove"
alias flat_i="flatpak install"

# lsd
alias ls='lsd'
alias lsa="lsd -a"

#tar
alias zpc="tar czf"
alias zpx="tar xvf"

# sys maintanence 
alias sup="sudo apt update && sudo apt full-upgrade && sudo apt autoclean && sudo apt autopurge"

# listen music 
alias lmusic='cd ~/Music/ && rg --files --glob "*.mp3" | fzf --multi --reverse --prompt="Song: " | xargs mpv --audio-display=no' 

# sys update 
alias syu="sudo apt update && sudo apt upgrade && sudo apt autoclean && sudo apt autopurge && sudo apt autoremove"

# lynx
alias ahref='lynx -dump -nonumbers -list-only'

# folder size management
alias fsize="du -had1 | sort -hr"

## foldershortcuts 
alias ob="cd /$HOME/Documents/workspace/static_website/hugo/gokayburuc_weblog/"
alias og="cd /$HOME/Documents/workspace/static_website/mdbook/golang_cookbook/"
alias odc="cd /$HOME/Documents/"
alias ol="cd /$HOME/Documents/logseq-logs/"
alias ov="cd /$HOME/Documents/vaults/secondbrain/"
alias ow="cd /$HOME/Documents/workspace"
alias ok="cd /$HOME/.config/kitty/"
alias oc="cd /$HOME/.config/nvim/"
alias odw="cd /$HOME/Downloads/"
alias oa="cd /$HOME/Documents/ankiweb/"

# bat 
alias bat="bat -pp"

# lazygit 
alias lg="lazygit"

# lazydocker 
alias lzd='lazydocker'

# brightness - reduce the brightness
alias loff="sudo brightnessctl set 75%"

# FLATPAK runners 
alias obsidian='flatpak run md.obsidian.Obsidian'
alias minder='flatpak run com.github.phase1geo.minder'

# WARN: use this to hide api keys 
# get keys from external file 
source ~/.keys.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# zoxide
eval "$(zoxide init zsh)"

#=============================== CUSTOM FUNCTIONS =============================== 

# NOTE: LEAP INTO ANY FILE 

leap() {
  fd --hidden --follow | fzf --reverse --prompt="Filename: " | xargs nvim
}



## INFO: FFMPEG CONVERTER
convert_webp() {
  for i in *
  do
    ## INFO: if extension is sh then do this
    if [[ "${i##*.}" == "webp" ]]; then
      echo "PDF FILE => $i"
      # FIX: show filename ,
      filename="${i%.*}"
      # FIX: show Extension 
      extension="${i##*.}"

      ## webp converter 
      ffmpeg -i "$filename" "$filename.png"

    fi
  done

    # ffmpeg -i "$1" "$2.png"
  }


## INFO: filename converter 

fcon ()
{
for i in $(rg --files); do

  new=$(echo "$i" | tr "[:upper:]" "[:lower:]" |  tr " " "-" | tr "_" "-" | tr "ı" "i" | tr "ş" "s" | tr "ğ" "g" | tr "ü" "u" | tr "ö" "o" | tr "ç" "c" )
  echo "$new"

  mv "$i" "$new" 
  echo "Rename: '$i' -> '$new' "

done
}

## INFO: classify 

folderput(){
  # query
  query=$1 
  # folder 
  foldername=$2 

  md $foldername 

  fd "$query" --exec mv {} $foldername \;
}

# NOTE: vault new note 

vn(){
  ov  # open vault
  local filename="$1"
  if [[ -z "$filename" ]]; then
    echo "Usage: vn <filename>"
    return 1
  fi
  nvim "00_inbox/${filename}.md" # enter file-name and directly start writing 
}

# path 
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/Documents/workspace/bash/:$PATH"

## Elixir Kiex Path 
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"

# pnpm
export PNPM_HOME="/home/gokayburuc/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# INFO: rg & fzf 
# if type rg &> /dev/null; then
#   export FZF_DEFAULT_COMMAND='rg --files'
#   export FZF_DEFAULT_OPTS='-m --reverse --height 50% --border '
# fi


# INFO fzf & fd 
if type fd &> /dev/null; then
  export FZF_DEFAULT_COMMAND='fd'
  export FZF_DEFAULT_OPTS='-m --reverse --height 50% --border '
fi
